# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM ubuntu:24.04

RUN apt-get -y update --allow-releaseinfo-change && \
  apt-get -y install --no-install-recommends python3 python3-dev \
  python3-pip build-essential python-is-python3 gdal-bin libgdal-dev pipenv pipx git && \
  rm -Rf /var/lib/apt/lists/* && \
  curl -sSf https://rye.astral.sh/get | bash

RUN python --version && python -m pipx ensurepath && pipx install uv pip-tools
