# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM ubuntu:20.04

ENV TZ=UTC
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update --allow-releaseinfo-change && \
  apt-get -y install --no-install-recommends python3 python3-dev python3-pip build-essential python-is-python3 gdal-bin libgdal-dev git && \
  rm -Rf /var/lib/apt/lists/*

RUN python --version && pip install --no-cache-dir pipenv uv pip-tools
