FROM ubuntu:23.04

RUN apt-get -y update --allow-releaseinfo-change && \
  apt-get -y install --no-install-recommends python3 python3-dev \
  python3-pip build-essential python-is-python3 gdal-bin libgdal-dev pipenv git && \
  rm -Rf /var/lib/apt/lists/*
